package main

import (
	"time"

	ebiten "github.com/hajimehoshi/ebiten/v2"
)

const (
	// size of the system window generated by Ebiten
	windowSizeWidth  = 1000
	windowSizeHeight = 1000

	// resolution of the canvas shown in the window
	windowResolutionHorizontal = 500
	windowResolutionVertical   = 500

	frameDuration = 0 * time.Millisecond

	numSeeds = 100
)

func main() {

	ebiten.SetWindowTitle("Voronoi Diagram")

	ebiten.SetWindowSize(windowSizeWidth, windowSizeHeight)

	voronoi, vErr := NewVoronoi(
		windowResolutionHorizontal,
		windowResolutionVertical,
		numSeeds,
	)
	if vErr != nil {
		panic(vErr)
	}

	g, gErr := NewCanvas(
		windowResolutionHorizontal,
		windowResolutionVertical,
		frameDuration,
		voronoi,
	)
	if gErr != nil {
		panic(gErr)
	}

	if err := ebiten.RunGame(g); err != nil {
		panic(err)
	}
}
