package main

import (
	ebiten "github.com/hajimehoshi/ebiten/v2"
)

const (
	// size of the system window generated by Ebiten
	windowSizeWidth  = 1000
	windowSizeHeight = 1000

	// resolution of the canvas shown in the window
	windowResolutionHorizontal = 500
	windowResolutionVertical   = 500

	// if true, this flag show only the final result of the voronoi tessellation
	hideIterations = false

	// number of randomly generated seeds for the voronoi diagram
	numSeeds = 30
)

func main() {

	ebiten.SetWindowTitle("Voronoi Diagram")

	ebiten.SetWindowSize(windowSizeWidth, windowSizeHeight)

	voronoi, vErr := NewVoronoi(
		windowResolutionHorizontal,
		windowResolutionVertical,
		numSeeds,
	)
	if vErr != nil {
		panic(vErr)
	}

	g, gErr := NewCanvas(
		windowResolutionHorizontal,
		windowResolutionVertical,
		hideIterations,
		voronoi,
	)
	if gErr != nil {
		panic(gErr)
	}

	if err := ebiten.RunGame(g); err != nil {
		panic(err)
	}
}
